<a href="https://colab.research.google.com/github/imhyunho99/2023-1--Deaplearning_Framework/blob/main/3_0_%EC%95%8C%EC%95%84%EB%91%90%EB%A9%B4_%EC%A2%8B%EC%9D%80_%EA%B8%B0%EB%B3%B8_%ED%85%90%EC%84%9C_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install torch torchvision #torch, torch 시각화화
import torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### 1) Random Numbers
- torch.rand()
- torch.randn()
- torch.randint()

In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=rand#torch.rand
# torch.rand(sizes) -> [0,1)
# 0에서 1사이의 랜덤한 숫자
x = torch.rand(2,3)
print("rand:", x)

# https://pytorch.org/docs/stable/torch.html?highlight=randn#torch.randn
# Random Normal
# 정규분포에서 샘플링한 값
x = torch.randn(2,3)
print("randn:", x)


# https://pytorch.org/docs/stable/torch.html?highlight=rand#torch.randint
# Random Integer
# 시작과 끝 사이의 랜덤한 자연수
x = torch.randint(2,5,size=(2,3))
print("randint:", x)

rand: tensor([[0.8638, 0.8763, 0.9034],
        [0.4483, 0.9358, 0.9809]])
randn: tensor([[ 1.9468,  1.6434, -0.8423],
        [-0.5557, -2.1574,  0.0406]])
randint: tensor([[3, 3, 4],
        [4, 2, 3]])



### 2) zeros & ones
- torch.ones()
- torch.ones_like()
- torch.zeros()
- torch.zeros_like(

In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=zeros#torch.zeros
# torch.zeros(2,3) -> [[0,0,0],[0,0,0]]
# 0으로 채워진 텐서
x = torch.zeros(2,3)
print("zeros:", x)

# https://pytorch.org/docs/stable/torch.html?highlight=zeros#torch.zeros_like
# same shape tensor filled with zeros
# 인자로 들어오는 텐서와 형태가 같은 0으로 채워진 텐서
ref = torch.rand(4,5)
x = torch.zeros_like(ref)
print("zeros_like:", x)

zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
zeros_like: tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


### 3) Tensor Data Type

- tensor.type()
- tensor.type_as()

In [ ]:
# https://pytorch.org/docs/stable/tensors.html?highlight=type#torch.Tensor.type
# without dtype, returns type of tensor
# tensor.type()은 해당 텐서의 타입을 리턴하고 type(tensor)는 토치의 텐서 클래스라는 것을 리턴함

x = torch.rand(2,3)
print(x)
print(x.type())
print(type(x))

# with dtype, cast the object to the dtype
# tensor.type()을 dtype과 함께 사용하면 텐서의 데이터 타입을 dtype에 넣어준 데이터 타입으로 바꿔줍니다.
double_x = x.type(dtype=torch.DoubleTensor)
print(double_x.type())

# https://pytorch.org/docs/stable/tensors.html?highlight=type#torch.Tensor.type_as
# 위의 type 함수와 유사하게 type_as라는 함수를 사용해 데이터타입을 바꿀 수 있습니다.
int_x = x.type_as(torch.IntTensor())
print(int_x.type())

tensor([[0.6865, 0.3973, 0.7378],
        [0.1752, 0.2693, 0.1975]])
torch.FloatTensor
<class 'torch.Tensor'>
torch.DoubleTensor
torch.IntTensor


### 4) Numpy to Tensor, Tensor to Numpy
- torch.from_numpy()
- tensor.numpy()
`

In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=from_numpy#torch.from_numpy
# torch.from_numpy(ndarray) -> tensor
# from_numpy 함수를 이용해 넘파이 배열을 토치텐서로 바꿀 수 있습니다.

import numpy as np

x1 = np.ndarray(shape=(2,3), dtype=int,buffer=np.array([1,2,3,4,5,6]))
print(x1)
x2 = torch.from_numpy(x1)
print(x2)

print(x2,x2.type())

# https://pytorch.org/docs/stable/tensors.html?highlight=numpy#torch.Tensor.numpy
# tensor.numpy() -> ndarray
# 반대로 토치 텐서를 .numpy() 를 통해 넘파이 배열로 바꿀 수 있습니다.

x3 = x2.numpy()
print(x3)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]]) torch.LongTensor
[[1 2 3]
 [4 5 6]]


### 5) Tensor on CPU & GPU



In [ ]:
# 배열을 인자로 넣어 토치 텐서를 생성할 수 있습니다.

x = torch.FloatTensor([[1,2,3],[4,5,6]])
print(x)


# https://pytorch.org/docs/stable/cuda.html?highlight=device#torch.cuda.device
# device 함수를 사용해 텐서를 원하는 장치로 이동시킬 수 있습니다.
cpu = torch.device('cpu')
gpu = torch.device('cuda')

# https://pytorch.org/docs/stable/cuda.html?highlight=available#torch.cuda.is_available
# gpu가 사용 가능한지 체크해줍니다.
if torch.cuda.is_available():
  # https://pytorch.org/docs/stable/tensors.html?highlight=#torch.Tensor.to
  # .to 함수를 이용해 지정한 장치로 이동시켜줍니다.
  x_gpu = x.to(gpu)
  print(x_gpu)
  
x_cpu = x_gpu.to(cpu)
print(x_cpu)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### 6) Tensor Size

In [ ]:
# https://pytorch.org/docs/stable/tensors.html?highlight=size#torch.Tensor.size
# size 함수를 이용해 텐서의 형태를 알 수 있습니다.
x = torch.FloatTensor(10,12,3,3)
x.size(), x.size()[1:2]



(torch.Size([10, 12, 3, 3]), torch.Size([12]))

## 2. Indexing, Joining, Slicing & Squeezing

### 1) Indexing

- torch.index_select()
- torch.masked_select()

In [ ]:
# 임의의 텐서를 생성합니다.
x = torch.randn(4,3)
print(x)

# middle 2 rows
# 토치 텐서 역시 기존 파이썬 인덱싱을 똑같이 쓸 수 있습니다.
print(x[1:3,:])


# https://pytorch.org/docs/stable/torch.html?highlight=index_select#torch.index_select
# index select along dimension 1
# index_select 함수를 사용해 지정한 차원 기준으로 원하는 값들을 뽑아낼 수 있습니다.

selected = torch.index_select(x,dim=1,index=torch.LongTensor([0,2]))
print(selected)

# https://pytorch.org/docs/stable/torch.html?highlight=masked_select#torch.masked_select
# torch.masked_select(input, mask)
# masked_select를 통해 뽑고자 하는 값들을 마스킹해서 선택할 수 있습니다.

x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1],[0,1,0]])
out = torch.masked_select(x,mask)

print(x, mask, out, sep="\n\n") # "sep ="  option

tensor([[-0.7420, -0.5884,  0.8216],
        [ 2.0630, -1.6659,  0.6631],
        [-1.5437, -4.7006,  1.4802],
        [-1.1453, -1.6023,  0.2276]])
tensor([[ 2.0630, -1.6659,  0.6631],
        [-1.5437, -4.7006,  1.4802]])
tensor([[-0.7420,  0.8216],
        [ 2.0630,  0.6631],
        [-1.5437,  1.4802],
        [-1.1453,  0.2276]])
tensor([[ 0.4521, -0.6687, -0.0555],
        [-0.5319,  1.0292,  0.2130]])

tensor([[0, 0, 1],
        [0, 1, 0]], dtype=torch.uint8)

tensor([-0.0555,  1.0292])


<ipython-input-14-9eeb1481e117>:23: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:1729.)
  out = torch.masked_select(x,mask)


### 2) Joining
- torch.cat()
- torch.stack()

In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=torch%20cat#torch.cat
# torch.cat(seq, dim=0) -> concatenate tensor along dim
# cat 함수를 이용해 텐서를 원하는대로 붙일 수 있습니다.
# cat은 concatenate의 약자입니다.

x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y],dim=0) #dim = 0 --> 행
z2 = torch.cat([x,y],dim=1) #dim = 1 --> 열열

print(x,y,z1,z2,sep="\n\n")

# https://pytorch.org/docs/stable/torch.html?highlight=torch%20stack#torch.stack
# torch.stack(sequence,dim=0) -> stack along new dim
# stack 함수를 통해 텐서를 붙일수도 있습니다.

x = torch.FloatTensor([[1,2,3],[4,5,6]])
x_stack = torch.stack([x,x,x,x],dim=0) #3차원 텐서 생성으로 이어붙이기기

print(x_stack,x_stack.size(),sep="\n\n")

tensor([[1., 2., 3.],
        [4., 5., 6.]])

tensor([[-1., -2., -3.],
        [-4., -5., -6.]])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])

tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]])
tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

torch.Size([4, 2, 3])


### 3) Slicing
- torch.chunk()
- torch.split()


In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=chunk#torch.chunk
# torch.chunk(tensor, chunks, dim=0) -> tensor into number of chunks
# chunk 함수를 통해 텐서를 원하는 chunk 개수만큼으로 분리할 수 있습니다.

x_1, x_2 = torch.chunk(z1,2,dim=0)
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

print(z1,x_1,x_2,z1,y_1,y_2,y_3,sep="\n")

# https://pytorch.org/docs/stable/torch.html?highlight=split#torch.split
# torch.split(tensor,split_size,dim=0) -> split into specific size
# split 함수를 통해 원하는 사이즈로 텐서를 자를 수 있습니다.

x1,x2 = torch.split(z1,2,dim=0)
y1 = torch.split(z1,2,dim=1) 

print(z1,x1,x2,sep="\n")

print("\nThis is y1:")
for i in y1:
  print(i)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.],
        [ 4.],
        [-1.],
        [-4.]])
tensor([[ 2.],
        [ 5.],
        [-2.],
        [-5.]])
tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-1., -2., -3.],
        [-4., -5., -6.]])

This is y1:
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [-1., -2.],
        [-4., -5.]])
tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]])


### 4) squeezing

In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=squeeze#torch.squeeze
# torch.squeeze(input,dim=None) -> reduce dim by 1
# squeeze 함수를 통해 길이가 1인 차원들을 압축시킬 수 있습니다.

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

print(x1.size(),x2.size(),sep="\n")

# https://pytorch.org/docs/stable/torch.html#torch.unsqueeze
# torch.unsqueeze(input,dim=None) -> add dim by 1
# squeeze와 반대로 unsqueeze를 통해 차원을 늘릴수 있습니다.

x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

print(x1.size(),x2.size(),sep="\n")

torch.Size([10, 1, 3, 1, 4])
torch.Size([10, 3, 4])
torch.Size([10, 3, 4])
torch.Size([1, 10, 3, 4])


## 3. Initialization
- 텐서 값 초기화

In [ ]:
# _(underbar) refers to in-place operation -> https://discuss.pytorch.org/t/what-is-in-place-operation/16244
import torch.nn.init as init

# https://pytorch.org/docs/stable/nn.html?highlight=init%20uniform#torch.nn.init.uniform_
# uniform 분포를 따라 텐서를 초기화 할 수 있습니다.
x1 = init.uniform_(torch.FloatTensor(3,4),a=0,b=9) 

# https://pytorch.org/docs/stable/nn.html?highlight=init%20uniform#torch.nn.init.normal_
# 정규 분포를 따라 텐서를 초기화 할 수 있습니다.
x2 = init.normal_(torch.FloatTensor(3,4),std=0.2)

# https://pytorch.org/docs/stable/nn.html?highlight=init%20uniform#torch.nn.init.constant_
# 지정한 값으로 텐서를 초기화 할 수 있습니다.
x3 = init.constant_(torch.FloatTensor(3,4),3.1415)

print("uniform:", x1 ,"\nnormla:",x2,"\nconstant(pi):",x3)

uniform: tensor([[6.2776, 2.4912, 3.1313, 4.3700],
        [2.7677, 4.8571, 7.9920, 5.3643],
        [7.0058, 3.9472, 3.0055, 5.0449]]) 
normla: tensor([[ 0.1385,  0.2692, -0.1271,  0.3586],
        [-0.1821,  0.1808, -0.4354,  0.1143],
        [-0.1528,  0.0675, -0.0607, -0.1284]]) 
constant(pi): tensor([[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]])


## 4. Math Operations

### 1) Arithmetic operations


In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=add#torch.add
# torch.add()
# 더하기 연산

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1,x2)

print(x1,x2,add,x1+x2,x1-x2,sep="\n")

# torch.add() broadcasting
# 더하기 연산의 브로드캐스팅

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.add(x1,10) #모든 항목에 10씩 뿌리기

print(x1,x2,x1+10,x2-10,sep="\n")

# https://pytorch.org/docs/stable/torch.html?highlight=add#torch.mul
# torch.mul() -> element-wise multiplication 
# size better match
# 곱하기 연산입니다. 각각의 요소간 곱이기 때문에 사이즈가 일치해야 연산이 가능합니다.
# 행렬 곱X 자리끼리 곱하기 연산
x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)

print(x3)

# torch.mul() -> broadcasting
# 곱하기 연산의 브로드캐스팅

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = x1*10
#모든 항목에 10씩 곱하기
print(x2)

# https://pytorch.org/docs/stable/torch.html?highlight=add#torch.div
# torch.div() -> size better match
# 나누기 연산. 각각의 요소간 나누기이기 때문에 사이즈가 일치해야 연산이 가능합니다.

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)

print(x3)

# torch.div() -> broadcasting
# 나누기 연산의 브로드캐스팅

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(x1/5)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[11., 12., 13.],
        [14., 15., 16.]])
tensor([[11., 12., 13.],
        [14., 15., 16.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[10., 20., 30.],
        [40., 50., 60.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])


In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=add#torch.pow
# torch.pow(input,exponent)
# 파워 연산(x의 n승)

x1 = torch.FloatTensor(3,4)
x2 = torch.pow(x1,2),x1**2
print(x2)

# https://pytorch.org/docs/stable/torch.html?highlight=add#torch.exp
# torch.exp(tensor,out=None) 
# exponential 연산

x1 = torch.FloatTensor(3,4)
x2 = torch.exp(x1)
print(x2)
# https://pytorch.org/docs/stable/torch.html?highlight=add#torch.log
# torch.log(input, out=None) -> natural logarithm
# 로그 연산

x1 = torch.FloatTensor(3,4)
x2 = torch.log(x1)
print(x2)

(tensor([[9.2694e+04, 0.0000e+00, 1.1755e-38, 2.8900e+00],
        [4.0000e+00, 3.1506e+00, 1.1755e-38, 3.3306e+00],
        [0.0000e+00, 3.5156e+00, 4.0000e+00, 3.6100e+00]]), tensor([[9.2694e+04, 0.0000e+00, 1.1755e-38, 2.8900e+00],
        [4.0000e+00, 3.1506e+00, 1.1755e-38, 3.3306e+00],
        [0.0000e+00, 3.5156e+00, 4.0000e+00, 3.6100e+00]]))
tensor([[1.4394, 1.0000,    inf, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000]])
tensor([[ -1.0100, -92.8884,   5.7159,     -inf],
        [  0.0000,   0.0000,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000,   1.2837]])


### 3) Matrix Operations

In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=add#torch.mm
# torch.mm(mat1, mat2) -> matrix multiplication
# 행렬곱 연산

x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)

torch.mm(x1,x2)

tensor([[1.3266e-01, 1.3534e-38, 9.1539e+04, 0.0000e+00, 5.5718e-33],
        [6.2719e-38, 0.0000e+00, 3.2646e-17, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 5.4431e-41, 0.0000e+00, 0.0000e+00]])

In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=add#torch.bmm
# torch.bmm(batch1, batch2) -> batch matrix multiplication
# 배치 행렬곱 연산. 맨 앞에 batch 차원은 무시하고 뒤에 요소들로 행렬곱을 합니다.

x1 = torch.FloatTensor(10,3,4)
x2 = torch.FloatTensor(10,4,5)

torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=add#torch.dot
# torch.dot(tensor1,tensor2) -> dot product of two tensor
# 두 텐서간의 프로덕트 연산

x1 = torch.tensor([2, 3])
x2 = torch.tensor([2, 1])

torch.dot(x1,x2)

tensor(7)

In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=add#torch.t
# torch.t(matrix) -> transposed matrix
# 행렬의 전치

x1 = torch.tensor([[1,2],[3,4]])
print(x1,x1.t(),sep="\n")

tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])


In [ ]:
# https://pytorch.org/docs/stable/torch.html?highlight=add#torch.transpose
# torch.transpose(input,dim0,dim1) -> transposed matrix
# 차원을 지정할 수 있는 행렬의 전치 연산

x1 = torch.FloatTensor(10,3,4)
print(x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size(),sep="\n")

print("\n 0번 차원과 2번 차원 전치\n")
print(x1.size(), torch.transpose(x1,0,2).size(), x1.transpose(0,2).size(), sep="\n\n")

torch.Size([10, 3, 4])
torch.Size([10, 4, 3])
torch.Size([10, 4, 3])

 0번 차원과 2번 차원 전치

torch.Size([10, 3, 4])

torch.Size([4, 3, 10])

torch.Size([4, 3, 10])
